### ISSUE TITLE
Readme

### ISSUE THREAD

**Issue by KoopReynders** [TheKevSter35/browser-technologies-1920#2]
Het doel van deze opdracht is te leren hoe je een online interactieve toepassing zo kan maken met behulp van Progressive Enhancement en Feature Detection dat deze het altijd doet ...

Er is een Readme toegevoegd met daarin:
1. Een (wireflow) schets van de functionaliteit met een beschrijving van de core functionality. Met een beschrijving en uitleg van de functional/reliable, usable en pleasurable laag.

_Keurig uitgelegd hoe de lagen werken._

2. Een beschrijving van de feature(s)/Browser Technologies. Welke browser de feature(s) wel/niet ondersteunen

_Goed de verschillende Feuture detects/flaaback bescheven. Ik lees geen feature detect in javascript, it die niet in je website?_

3. Een conclusie waar je in gaat op de leerdoelen en criteria en hoe je dit hebt gehaald. Dit is je bewijsvoering voor het vak.

_Ik mis een conclusie waar je in gaat op de leerdoelen en criteria en hoe je dit hebt gehaald. Dit is je bewijsvoering voor het vak. Dit moet je nog toevoegen._

**Comment by TheKevSter35** [comment]
Ik heb de conclusie toegevoegd

**Comment by KoopReynders** [comment]
Conclusie is prima. Leuk om te lezen. 
Je kan een volgende keer in gaan op de leerdoelen en criteria en hoe je dit hebt gehaald.

**Comment by TheKevSter35** [comment]
zal ik doen :)
